---
#Change parameters

- name: "Set {{current_param.group}}.{{current_param.name}} = {{param}} in model config"
  copy:
    content: "{{ modelparams | combine({'numenta':{ 'modelConfig':{ 'modelParams': { current_param.group: { current_param.name : param } } } } }, recursive=true) | to_json }}"
    dest: "{{ output_config_location }}"
  when: encoder == False

- name: "Set {{current_param.group}}.{{current_param.name}} = {{param}} in model config"
  copy:
    content: "{{ modelparams | combine({'numenta':{ 'modelConfig':{ 'modelParams': { 'sensorParams': { 'encoders': { current_param.group: { current_param.name : param } } } } } } }, recursive=true) | to_json }}"
    dest: "{{ output_config_location }}"
  when: encoder == True  
  
- name: write parameters of current run to file
  copy:
    content: "[{{ current_param | combine({'range': param }, recursive=true) | to_json }}]"
    dest: "{{ django_location }}/parametervalues.json"

- name: "run NAB for current parameter settings"
  command: "python run.py -d null,numenta -m config/paramsweep_detectorparams.json --skipConfirmation"
  args:
    chdir: "{{ NAB_location }}"


- name: "process NAB results"
  command: python3 manage.py addresult --parametersFile parametervalues.json
  args:
    chdir: "{{ django_location }}"

