- hosts: localhost
  vars:
    #test each parameter seperately
    single_parameter: True
    #We are changing encoder settings (special case)
    encoder: True
    params:      
      - name: "timeOfDay"
        group: "timestamp_timeOfDay"
        range: [[21,1],[21,2],[21,3],[21,4],[21,5],[21,6],[21,7],[21,8],[21,9],[21,9.49],[21,10],[21,11],[21,12]]
      - name: "n"
        group: "value"
        range: [300,350,400,450,500]
      - name: "seed"
        group: "value"
        range: [1,13,42,1991,2019]
      # - name: "columnCount"
      #   group: "spParams"
      #   range: [512,1024,1536,2560,4096] #tm has to match!
      # - name: "seed"
      #   group: "spParams"
      #   range: [42,1234,6793,1,17]
    modelparams: "{{ lookup('file','{{ config_location }}') | from_json }}"

  tasks:
    # - name: include temporal memory sweep parameters
    #   include_vars:
    #     file: group_vars/tm.yml
    - name: echo
      debug:
        msg: "{{ params }}"
    - name: Single parameter sweep
      include_role:
        name: single_param_sweep
      with_items:
        - "{{ params }}"
      loop_control:
        loop_var: current_param
      when: single_parameter == True
      
    # - name: Multiple parameter sweep
    #   include_role:
    #     name: multiple_param_sweep
    #   with_indexed_items:
    #     - "{{ params | dict2items }}"
    #   loop_control:
    #     loop_var: index

    # - name: debugging etc
    #   debug:
    #     msg: "{{ (params | dict2items) }}"
